In [215]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from functools import reduce

In [271]:
# read the files
no_DNF_results_data_file = pd.read_csv(r"..\cleaned_data\f1db-races-race-results-NO-DNF.csv")
results_data_file = pd.read_csv(r"..\cleaned_data\f1db-races-race-results-CLEANED.csv")
quals_data_file = pd.read_csv(r"..\cleaned_data\f1db-races-qualifying-results-CLEANED.csv")
free_practice_1_data = pd.read_csv(r"..\cleaned_data\f1db-races-free-practice-1-results-CLEANED.csv")
free_practice_2_data = pd.read_csv(r"..\cleaned_data\f1db-races-free-practice-2-results-CLEANED.csv")
free_practice_3_data = pd.read_csv(r"..\cleaned_data\f1db-races-free-practice-3-results-CLEANED.csv")
free_practice_4_data = pd.read_csv(r"..\cleaned_data\f1db-races-free-practice-4-results-CLEANED.csv")
abs_grid_delta_data = pd.read_csv(r"..\cleaned_data\mean-absolute-position-difference-no-DNF.csv")
start_position_data_file = pd.read_csv(r"..\data_f1db\f1db-races-starting-grid-positions.csv")
start_position_data_file = start_position_data_file[
    (start_position_data_file['year'] > 1985) & (start_position_data_file['year'] < 2025)
    ]
all_race_results_data = pd.read_csv(r"..\data_f1db\f1db-races-race-results.csv")

races_data_file = pd.read_csv(r"..\data_f1db\f1db-races.csv")
circuits_data_file = pd.read_csv(r"..\data_f1db\f1db-circuits.csv")

# Create list of unique race ids
race_id_list = no_DNF_results_data_file['raceId'].unique()

fp3_lap_data_data = free_practice_3_data[free_practice_3_data['laps']>0]
fp_lap_race_id_list = fp3_lap_data_data['raceId'].unique()

C:\Users\patri\AppData\Local\Temp\ipykernel_12152\3763636759.py:14: DtypeWarning: Columns (31,32) have mixed types. Specify dtype option on import or set low_memory=False.
  all_race_results_data = pd.read_csv(r"..\data_f1db\f1db-races-race-results.csv")

In [231]:
# Generate data which tracks the number of racers a driver has participated in before the current race

# Step 1: Select and sort race-driver records
race_years = races_data_file[["id", "year"]].rename(columns={"id": "raceId"})
race_driver_pairs = results_data_file[["raceId", "driverId"]]
combined = pd.merge(race_driver_pairs, race_years, on="raceId", how="left")

# Step 2: Sort by year and raceId (just in case)
combined = combined.sort_values(by=["driverId", "year", "raceId"])

# Step 3: Compute number of prior races for each driver
combined["racesBefore"] = (
    combined.groupby("driverId").cumcount()
)

# Step 4: Optional - rename for clarity or save as desired
racer_racecount = combined[["year", "raceId", "driverId", "racesBefore"]]
racer_racecount.to_csv("f1-driver-race-counts.csv", index=False)

In [213]:
# Get average local position change for each race id
# Write a function to generate ALS for an input of race_id list

def get_correct_positions(position):
    position_copy = position.copy()
    n = len(position)

    for y in range(n):
        if y+1 in position:
            position_copy_index = position_copy.index(y+1)
            position_copy.pop(position_copy_index)
        if y+1 not in position:
            position_copy.sort()
            for z in range(len(position_copy)):
                position_index = position.index(position_copy[z])
                position[position_index] = y+1
                y += 1
            break

    return position

def generate_ALPC_data(input_race_id_list):
    avg_local_pos = []

    for race_id in input_race_id_list:
        race_data = no_DNF_results_data_file[
            (no_DNF_results_data_file['raceId'] == race_id) & 
            (no_DNF_results_data_file['positionDisplayOrder'] > 0)
        ]

        # Get final positions
        final_positions = race_data['positionDisplayOrder'].tolist()
        n = len(final_positions)

        if n < 2:
            avg_local_pos.append(0.0)
            continue

        true_final_positions = get_correct_positions(final_positions)

        this_sum = 0
        for i in range(n):
            summand = 0
            for j in range(n):
                if i == j: continue
                local_change = (i - j) - (true_final_positions.index(i+1) - true_final_positions.index(j+1))
                summand += local_change
            this_sum += abs(summand)

        # Normalize by number of pairs
        #this_sum *= 2  # because we only looped over i < j
        avg = this_sum / (n * (n - 1))
        avg_local_pos.append({'raceId': race_id, 'ALPC': avg})

    return pd.DataFrame(avg_local_pos)
generate_ALPC_data(race_id_list)

     raceId      ALPC
0       421  2.444444
1       422  0.571429
2       423  1.500000
3       424  1.454545
4       425  3.166667
..      ...       ...
700    1121  2.000000
701    1122  3.857143
702    1123  2.352941
703    1124  2.428571
704    1125  3.875000

[705 rows x 2 columns]

In [208]:
cumulative_data_file = pd.read_csv(r"..\Patrick\f1-racer-cumulative-points.csv")

def get_avg_cum_racer_points(input_race_id_list):
    avg_cum_racer_points = []

    for race_id in input_race_id_list:
        this_race = cumulative_data_file[cumulative_data_file['raceId'] == race_id]
        cum_racer_points = list(this_race['cumulativePoints'])
        this_race_avg = sum(cum_racer_points)/len(cum_racer_points)

        avg_cum_racer_points.append({'raceId': race_id, 'averageCumRacerPoints': this_race_avg})

    return pd.DataFrame(avg_cum_racer_points)
get_avg_cum_racer_points(race_id_list)

     raceId  averageCumRacerPoints
0       421              75.260000
1       422              76.260000
2       423              74.288462
3       424              75.250000
4       425              74.380000
..      ...                    ...
700    1121             985.825000
701    1122             981.575000
702    1123             996.025000
703    1124            1001.125000
704    1125             997.275000

[705 rows x 2 columns]

In [209]:
# Get total number of DNF's for each race
# Write a function that generates total number of DNF's for a given race_id list

def generate_DNFs(input_race_id_list):
    total_num_DNFS = []

    for race_id in input_race_id_list:
        no_DNF_race_data = no_DNF_results_data_file[no_DNF_results_data_file['raceId'] == race_id]
        general_race_data = results_data_file[results_data_file['raceId'] == race_id]
        no_of_DNFs = 0

        for x in general_race_data['positionText']:
            if x == 'DNF':
                no_of_DNFs += 1

        total_num_DNFS.append({'raceId': race_id, 'totalDNFs': no_of_DNFs})
    
    return pd.DataFrame(total_num_DNFS)

generate_DNFs(race_id_list)

     raceId  totalDNFs
0       421         15
1       422         17
2       423         16
3       424          8
4       425         12
..      ...        ...
700    1121          3
701    1122          2
702    1123          2
703    1124          5
704    1125          3

[705 rows x 2 columns]

In [346]:
# Compute the Average Local Position Difference (ALPS) between Fastest Qualifying Time grid and the Starting Grid

quals_data_file['minQualTime'] = quals_data_file[['timeMillis', 'q1Millis', 'q2Millis', 'q3Millis']].min(axis=1)

def generate_quals_ALPC_data(input_race_id_list):
    quals_avg_local_position = []

    for race_id in input_race_id_list:

        this_race_data = quals_data_file[quals_data_file['raceId'] == race_id]

        if this_race_data.isna().all(axis=1).all():
            quals_avg_local_position.append({'raceId': race_id, 'qualifyingALPC': np.nan})

        this_race_data = this_race_data.sort_values('minQualTime')
        this_race_start_data = start_position_data_file[start_position_data_file['raceId'] == race_id]
        this_race_start_data = this_race_start_data.sort_values('positionNumber')
        min_qual_time_list = this_race_data['driverId'].to_list()
        starting_grid = this_race_start_data['driverId'].to_list()

        n = len(starting_grid)
        m = len(min_qual_time_list)
        this_sum = 0

        if m != n: 
            common_drivers = set(min_qual_time_list) & set(starting_grid)
            min_qual_time_list = [x for x in min_qual_time_list if x in common_drivers]
            starting_grid = [y for y in starting_grid if y in common_drivers]
            n = len(starting_grid)

        for i in range(n):
            summand = 0
            for j in range(n):
                if j == i: continue
                driver_i = starting_grid[i]
                driver_j = starting_grid[j]
                summand += (i-j) - (min_qual_time_list.index(driver_i)-min_qual_time_list.index(driver_j))
            this_sum += abs(summand)


        this_sum = this_sum/(n * (n-1))
        quals_avg_local_position.append({'raceId': race_id, 'qualifyingALPC': this_sum})

    return pd.DataFrame(quals_avg_local_position)
generate_quals_ALPC_data(race_id_list)

     raceId  qualifyingALPC
0       421        0.000000
1       422        0.000000
2       423        0.000000
3       424        0.000000
4       425        0.000000
..      ...             ...
700    1121        0.105263
701    1122        1.294118
702    1123        1.368421
703    1124        0.210526
704    1125        1.473684

[705 rows x 2 columns]

In [211]:
racers_years_exp_data = pd.read_csv(r"..\Patrick\f1-racer-years-experience.csv")

def get_avg_years_exp(input_race_id_list):
    avg_years_exp = []

    for race_id in race_id_list:
        this_race_data = racers_years_exp_data[racers_years_exp_data['raceId'] == race_id]
        years_exp = list(this_race_data['driverExp'])
        avg_exp = sum(years_exp) / len(years_exp)
        avg_years_exp.append({'raceId': race_id, 'averageDriverExpYears': avg_exp})

    return pd.DataFrame(avg_years_exp)
get_avg_years_exp(race_id_list)

     raceId  averageDriverExpYears
0       421               4.360000
1       422               4.360000
2       423               4.400000
3       424               5.000000
4       425               4.160000
..      ...                    ...
700    1121               7.400000
701    1122               7.166667
702    1123               7.400000
703    1124               7.400000
704    1125               7.000000

[705 rows x 2 columns]

In [232]:
# Generate the average driver race count

race_count_data = pd.read_csv(r"..\Patrick\f1-driver-race-counts.csv")

def generate_avg_driver_race_count(input_race_id_list):
    average_race_count = []

    for race_id in input_race_id_list:
        this_race_data = race_count_data[race_count_data['raceId'] == race_id]
        race_count = list(this_race_data['racesBefore'])
        average_race_count.append({'raceId': race_id, 'avgDriverRaceCount': sum(race_count)/len(race_count)})

    return pd.DataFrame(average_race_count)
generate_avg_driver_race_count(race_id_list)

     raceId  avgDriverRaceCount
0       421            0.000000
1       422            1.000000
2       423            1.920000
3       424            3.000000
4       425            3.640000
..      ...                 ...
700    1121          160.950000
701    1122          155.277778
702    1123          162.800000
703    1124          163.800000
704    1125          157.000000

[705 rows x 2 columns]

In [277]:
# Gather circuit attribute data

new_circuit_data = races_data_file[['id', 'circuitType', 'direction']].copy()
new_circuit_data = new_circuit_data.rename(columns={'id': 'raceId'})
new_circuit_data = new_circuit_data[(new_circuit_data['raceId'] > 420) & (new_circuit_data['raceId'] < 1126)]
new_circuit_data

      raceId circuitType       direction
420      421        RACE  ANTI_CLOCKWISE
421      422        RACE       CLOCKWISE
422      423        RACE  ANTI_CLOCKWISE
423      424      STREET       CLOCKWISE
424      425        RACE       CLOCKWISE
...      ...         ...             ...
1120    1121        RACE       CLOCKWISE
1121    1122        RACE  ANTI_CLOCKWISE
1122    1123      STREET  ANTI_CLOCKWISE
1123    1124        RACE       CLOCKWISE
1124    1125        RACE  ANTI_CLOCKWISE

[705 rows x 3 columns]

In [261]:
def compute_top_ten_constructor_diversity(df):
    df = df.copy()
    df = df[df['positionNumber'] > 0]  # remove DNS (Did Not Start) or invalid grid values if needed
    diversity_list = []

    for race_id in df['raceId'].unique():
        race_data = df[df['raceId'] == race_id]
        top_10 = race_data.nsmallest(10, 'positionNumber')  # get top 10 starting grid positions
        constructors = top_10['constructorId'].nunique()  # count unique constructors
        diversity_list.append({'raceId': race_id, 'topTenDiversity': constructors})

    return pd.DataFrame(diversity_list)
compute_top_ten_constructor_diversity(start_position_data_file)

     raceId  topTenDiversity
0       421                6
1       422                5
2       423                6
3       424                9
4       425                7
..      ...              ...
700    1121                7
701    1122                7
702    1123                7
703    1124                6
704    1125                8

[705 rows x 2 columns]

In [293]:
updated_circuits_df = circuits_data_file[['id', 'countryId']].copy()
updated_circuits_df = updated_circuits_df.rename(columns={'id': 'circuitId'})
updated_circuits_df

     circuitId             countryId
0     adelaide             australia
1         aida                 japan
2     ain-diab               morocco
3      aintree        united-kingdom
4   anderstorp                sweden
..         ...                   ...
72  yas-marina  united-arab-emirates
73     yeongam           south-korea
74   zandvoort           netherlands
75     zeltweg               austria
76      zolder               belgium

[77 rows x 2 columns]

In [315]:
fpdf = free_practice_1_data[['raceId', 'driverId', 'timeMillis']].rename(columns={'timeMillis': 'fp1Time'})

fpdf = fpdf.merge(
    free_practice_2_data[['raceId', 'driverId', 'timeMillis']].rename(columns={'timeMillis': 'fp2Time'}),
    on=['raceId', 'driverId'],
    how='left'
)

fpdf = fpdf.merge(
    free_practice_3_data[['raceId', 'driverId', 'timeMillis']].rename(columns={'timeMillis': 'fp3Time'}),
    on=['raceId', 'driverId'],
    how='left'
)

fpdf['min_fp_time'] = fpdf[['fp1Time', 'fp2Time', 'fp3Time']].min(axis=1)
fpdf['min_fp_time'] = fpdf['min_fp_time'].fillna(1000000)
fpdf

       raceId         driverId  fp1Time  fp2Time  fp3Time  min_fp_time
0         435    nelson-piquet  78601.0  78353.0      NaN      78353.0
1         435     ayrton-senna  78779.0  77977.0      NaN      77977.0
2         435   gerhard-berger  79004.0  78088.0      NaN      78088.0
3         435     keke-rosberg  79099.0  79160.0      NaN      79099.0
4         435    nigel-mansell  79588.0  78785.0      NaN      78785.0
...       ...              ...      ...      ...      ...          ...
14229    1125  fernando-alonso  85504.0  84574.0  84453.0      84453.0
14230    1125      liam-lawson  85563.0  84503.0  84519.0      84503.0
14231    1125  valtteri-bottas  85611.0  84230.0  84479.0      84230.0
14232    1125      guanyu-zhou  85921.0  84557.0  84668.0      84557.0
14233    1125      jack-doohan  86304.0  84961.0  84434.0      84434.0

[14234 rows x 6 columns]

In [338]:
fp_race_id_list = fpdf['raceId'].unique()

def get_free_practice_RALPC(input_race_id_list):
    fp_ralpc = []

    for race_id in input_race_id_list:
        if race_id not in fpdf['raceId'].unique():
            fp_ralpc.append({'raceId': race_id, 'FRALPC': np.nan})
            continue

        this_race_data = fpdf[fpdf['raceId'] == race_id]
        this_race_start_data = start_position_data_file[start_position_data_file['raceId'] == race_id]
        this_race_start_data = this_race_start_data.sort_values('positionNumber')
        update_race_df = this_race_data.sort_values('min_fp_time')
        driver_fp_pos = update_race_df['driverId'].to_list()
        starting_grid = this_race_start_data['driverId'].to_list()

        n = len(starting_grid)
        m = len(driver_fp_pos)
        total_sum = 0

        if m != n: 
            common_drivers = set(driver_fp_pos) & set(starting_grid)
            driver_fp_pos = [x for x in driver_fp_pos if x in common_drivers]
            starting_grid = [y for y in starting_grid if y in common_drivers]
            n = len(starting_grid)

        for i in range(n):
            summand = 0
            for j in range(n):
                if i == j: continue
                driver_i = starting_grid[i]
                driver_j = starting_grid[j]
                local_change = (i - j) - (driver_fp_pos.index(driver_i) - driver_fp_pos.index(driver_j))
                summand += local_change

            total_sum += abs(summand) / (n*(n-1))
        
        fp_ralpc.append({'raceId': race_id, 'FRALPC': total_sum})
    return pd.DataFrame(fp_ralpc) 

get_free_practice_RALPC(race_id_list)

     raceId    FRALPC
0       421       NaN
1       422       NaN
2       423       NaN
3       424       NaN
4       425       NaN
..      ...       ...
700    1121  3.714286
701    1122  4.705882
702    1123  4.315789
703    1124  5.052632
704    1125  3.538462

[705 rows x 2 columns]

In [347]:
# Step 1: Generate all your predictor DataFrames
alpc_df = generate_ALPC_data(race_id_list)
dnfs_df = generate_DNFs(race_id_list)
points_df = get_avg_cum_racer_points(race_id_list)
quals_alpc_df = generate_quals_ALPC_data(race_id_list)
exp_df = get_avg_years_exp(race_id_list)
race_count_df = generate_avg_driver_race_count(race_id_list)
top_div_df = compute_top_ten_constructor_diversity(start_position_data_file)
fralpc_df = get_free_practice_RALPC(race_id_list)

# Step 2: Merge all predictor DataFrames on 'raceId'
dataframes = [alpc_df, dnfs_df, points_df, quals_alpc_df, exp_df, race_count_df, top_div_df, fralpc_df]
combined_df = reduce(lambda left, right: pd.merge(left, right, on='raceId', how='outer'), dataframes)

# Step 3: Get circuitId info from races_data_file
race_metadata = races_data_file.rename(columns={'id': 'raceId'})[['raceId', 'circuitId']]

# Step 4: Merge circuitId into the combined DataFrame
combined_df = pd.merge(combined_df, race_metadata, on='raceId', how='left')

# Step 5: Reorder columns to place circuitId after raceId
cols = combined_df.columns.tolist()
if 'circuitId' in cols:
    cols.insert(cols.index('raceId') + 1, cols.pop(cols.index('circuitId')))
    combined_df = combined_df[cols]

complete_df = combined_df.merge(updated_circuits_df[['circuitId', 'countryId']], on='circuitId', how='left')

# Step 6: Optional sort by raceId
complete_df = complete_df.sort_values(by='raceId')

# Step 7: Export to CSV
complete_df.to_csv("race_predictor_data.csv", index=False)